export enum LogTypeEnum {
    NATS_STREAMING_MESSAGE_RCV = 'NATS_STREAMING_MESSAGE_RCV',
    NATS_STREAMING_MESSAGE_ACK = 'NATS_STREAMING_MESSAGE_ACK',
    MICROSERVICE_EXCEPTION = 'MICROSERVICE_EXCEPTION',
}
